// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, ClearCommand, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  ClearCommand = require('../lib/ClearCommand');

  adb = require('../adb');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('ClearCommand', function() {
    it("should send 'adb shell pm clear <right pkg>", function() {
      return client.clear('123456', 'com.achievo.vipshop', function(err, data) {
        if (err === null) {
          expect(err).to.be.a('null');
          return expect(data).to["true"];
        }
      }).then(function(data) {
        return expect(data).to["true"];
      })["catch"](function(err) {
        return expect(err).to.be.an["instanceof"](Error);
      });
    });
    return it("should send 'adb shell pm clear <wrong pkg>", function() {
      return client.clear('123456', 'com.achievo.vipshop1', function(err, data) {
        if (err === null) {
          expect(err).to.be.an["instanceof"](Error);
          return expect(data).to["false"];
        }
      }).then(function(data) {
        return expect(data).to["false"];
      })["catch"](function(err) {
        return expect(err).to.be.an["instanceof"](Error);
      });
    });
  });

}).call(this);

//# sourceMappingURL=ClearCommand.js.map
