// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  adb = require('../adb');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('GetFeaturesCommand', function() {
    return it("should send 'adb shell pm list features' <right>", function() {
      return client.getFeatures('123456', function(err, data) {
        if (err === null) {
          expect(data).to.be["instanceof"](Array);
          return expect(data).to.have.length.above(10);
        } else {
          expect(err).to.be.an["instanceof"](Error);
          return expect(err.message).to.equal('error: device not found.');
        }
      }).then(function(data) {
        expect(data).to.be["instanceof"](Array);
        return expect(data).to.have.length.above(10);
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('error: device not found.');
      });
    });
  });

}).call(this);

//# sourceMappingURL=GetFeaturesCommand.js.map
