// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  adb = require('../adb');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('IsInstalledCommand', function() {
    return it("should send 'adb isInstalled file' <right>", function() {
      return client.isInstalled('123456', 'com.achievo.vipshop', function(err, data) {
        if (err === null) {
          return expect(data).to.equal('/system/vendor/operator/app/vipshop_20160420/vipshop_20160420.apk');
        } else {
          expect(err).to.be.an["instanceof"](Error);
          return expect(err.message).to.equal('error: device not found.');
        }
      }).then(function(data) {
        return expect(data).to.equal('/system/vendor/operator/app/vipshop_20160420/vipshop_20160420.apk');
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('error: device not found.');
      });
    });
  });

}).call(this);

//# sourceMappingURL=IsInstalledCommand.js.map
