// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  adb = require('../adb');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('GetDHCPIpAddressCommand', function() {
    return it("should send 'adb shell getprop dhcp.<iface>.ipaddress' <right>", function() {
      return client.getDHCPIpAddress('123456', 'wlan0', function(err, data) {
        if (err === null) {
          return expect(data).to.equal('192.168.3.30');
        } else {
          expect(err).to.be.an["instanceof"](Error);
          return expect(err.message).to.equal('error: device not found.');
        }
      }).then(function(data) {
        return expect(data).to.equal('192.168.3.30');
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('error: device not found.');
      });
    });
  });

  describe('GetDHCPIpAddressCommand', function() {
    return it("should send 'adb shell getprop dhcp.<iface>.ipaddress' <wrong>", function() {
      return client.getDHCPIpAddress('123456', 'wlan1', function(err, data) {
        expect(data).to.be.empty;
        expect(err).to.be.an["instanceof"](Error);
        if (err.message.indexOf('ip') > -1) {
          return expect(err.message).to.equal('error:cannot find ip');
        } else {
          return expect(err.message).to.equal('error: device not found.');
        }
      }).then(function(data) {
        return expect(data).to.be.empty;
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('error: device not found.');
      });
    });
  });

}).call(this);

//# sourceMappingURL=GetDHCPIpAddressCommand.js.map
