// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  adb = require('../adb');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('GetPropertiesCommand', function() {
    return it("should send 'adb shell getprop' <right>", function() {
      return client.getProperties('123456', function(err, data) {
        if (err === null) {
          expect(data).to.be["instanceof"](Object);
          expect(data).to.have.property('af.rf_info');
          return expect(data).to.have.property('af.rf_info', '273');
        } else {
          expect(err).to.be.an["instanceof"](Error);
          return expect(err.message).to.equal('error: device not found.');
        }
      }).then(function(data) {
        expect(data).to.be["instanceof"](Object);
        expect(data).to.have.property('af.rf_info');
        return expect(data).to.have.property('af.rf_info', '273');
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('error: device not found.');
      });
    });
  });

}).call(this);

//# sourceMappingURL=GetPropertiesCommand.js.map
