// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, client, expect, ios;

  Chai = require('chai');

  expect = Chai.expect;

  ios = require('../ioskit');

  client = ios.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('GetPropertiesCommand', function() {
    return it("should send 'ideviceinfo -u UUID' <right>", function() {
      return client.getProperties('6dff3d0c838ae0275f1e4daa0f4757d9022d6ebd', function(err, data) {
        if (err === null) {
          console.log(data);
          expect(data).to.be["instanceof"](Object);
          expect(data).to.have.property('ActivationState');
          return expect(data).to.have.property('ActivationState', 'Activated');
        } else {
          expect(err).to.be.an["instanceof"](Error);
          return expect(err.message).to.equal('error: device not found.');
        }
      }).then(function(data) {
        expect(data).to.be["instanceof"](Object);
        expect(data).to.have.property('ActivationState');
        return expect(data).to.have.property('ActivationState', 'Activated');
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('error: device not found.');
      });
    });
  });

}).call(this);

//# sourceMappingURL=GetPropertiesCommand.js.map
