// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  adb = require('../adb');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('ClearCommand', function() {
    return it("should send 'adb devices' <right>", function() {
      return client.listDevices(function(err, data) {
        if (err === null) {
          return expect(data).to.equal('QLXBBCA671245055');
        } else {
          expect(err).to.be.an["instanceof"](Error);
          return expect(err.message).to.equal('can\'t find a device');
        }
      }).then(function(data) {
        return expect(data).to.equal('QLXBBCA671245055');
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('can\'t find a device');
      });
    });
  });

}).call(this);

//# sourceMappingURL=ListDevicesCommand.js.map
