// Generated by CoffeeScript 1.11.1
(function() {
  var Chai, Tracker, adb, client, expect;

  Chai = require('chai');

  expect = Chai.expect;

  adb = require('../adb');

  Tracker = require('../lib/Tracker');

  client = adb.createClient({
    host: 'localhost',
    port: 5078
  });

  describe('WaitForDeviceCommand', function() {
    return it("should send 'adb wait-for-device' <right>", function() {
      return client.waitForDevice('123456', function(err, data) {
        return expect(data).to.be.an["instanceof"](Tracker);
      }).then(function(data) {
        return expect(data).to.be.an["instanceof"](Tracker);
      })["catch"](function(err) {
        expect(err).to.be.an["instanceof"](Error);
        return expect(err.message).to.equal('can\'t find a device');
      });
    });
  });

}).call(this);

//# sourceMappingURL=WaitForDeviceCommand.js.map
