// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, ListDevicesWithPathsCommand, Promise,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  ListDevicesWithPathsCommand = (function(superClass) {
    extend(ListDevicesWithPathsCommand, superClass);

    function ListDevicesWithPathsCommand() {
      return ListDevicesWithPathsCommand.__super__.constructor.apply(this, arguments);
    }

    return ListDevicesWithPathsCommand;

  })(Command);

  module.exports = ListDevicesWithPathsCommand;

}).call(this);

//# sourceMappingURL=ListDevicesWithPathsCommand.js.map
