// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, OpenLogcatCommand, Promise,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  OpenLogcatCommand = (function(superClass) {
    extend(OpenLogcatCommand, superClass);

    function OpenLogcatCommand() {
      return OpenLogcatCommand.__super__.constructor.apply(this, arguments);
    }

    return OpenLogcatCommand;

  })(Command);

  module.exports = OpenLogcatCommand;

}).call(this);

//# sourceMappingURL=OpenLogcatCommand.js.map
