// Generated by CoffeeScript 1.11.1
(function() {
  var EventEmitter, Tracker,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('events').EventEmitter;

  Tracker = (function(superClass) {
    extend(Tracker, superClass);

    function Tracker() {
      return Tracker.__super__.constructor.apply(this, arguments);
    }

    Tracker.prototype.findDevice = function() {
      return this.emit('add');
    };

    return Tracker;

  })(EventEmitter);

  module.exports = Tracker;

}).call(this);

//# sourceMappingURL=Tracker.js.map
