// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, InstallRemoteCommand, Promise,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  InstallRemoteCommand = (function(superClass) {
    extend(InstallRemoteCommand, superClass);

    function InstallRemoteCommand() {
      return InstallRemoteCommand.__super__.constructor.apply(this, arguments);
    }

    return InstallRemoteCommand;

  })(Command);

  module.exports = InstallRemoteCommand;

}).call(this);

//# sourceMappingURL=InstallRemoteCommand.js.map
