// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, OpenLocalCommand, Promise,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  OpenLocalCommand = (function(superClass) {
    extend(OpenLocalCommand, superClass);

    function OpenLocalCommand() {
      return OpenLocalCommand.__super__.constructor.apply(this, arguments);
    }

    return OpenLocalCommand;

  })(Command);

  module.exports = OpenLocalCommand;

}).call(this);

//# sourceMappingURL=OpenLocalCommand.js.map
