// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, Promise, ShellCommand,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  ShellCommand = (function(superClass) {
    extend(ShellCommand, superClass);

    function ShellCommand() {
      return ShellCommand.__super__.constructor.apply(this, arguments);
    }

    ShellCommand.prototype.execute = function(callback) {
      var action, isSuccess, resolver, returnValue, spawn;
      resolver = Promise.defer();
      spawn = ChildProcess.spawn;
      action = spawn(this.cmd, this.args);
      isSuccess = null;
      returnValue = '';
      action.stdout.on('data', function(data) {
        var result;
        result = new Buffer(data).toString();
        return resolver.resolve(returnValue);
      });
      action.stderr.on('data', function(data) {
        isSuccess = true;
        return resolver.reject(new Buffer(data).toString());
      });
      action.on('close', function(data) {
        isSuccess = true;
        return resolver.resolve('close');
      });
      return resolver.promise["finally"](function() {
        return callback(isSuccess, returnValue);
      });
    };

    return ShellCommand;

  })(Command);

  module.exports = ShellCommand;

}).call(this);

//# sourceMappingURL=ShellCommand.js.map
