// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, Promise, TcpipCommand,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  TcpipCommand = (function(superClass) {
    extend(TcpipCommand, superClass);

    function TcpipCommand() {
      return TcpipCommand.__super__.constructor.apply(this, arguments);
    }

    return TcpipCommand;

  })(Command);

  module.exports = TcpipCommand;

}).call(this);

//# sourceMappingURL=TcpipCommand.js.map
