// Generated by CoffeeScript 1.11.1
(function() {
  var ChildProcess, Command, Promise, WaitBootCompleteCommand,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Promise = require('bluebird');

  Command = require('./Command');

  ChildProcess = require('child_process');

  WaitBootCompleteCommand = (function(superClass) {
    extend(WaitBootCompleteCommand, superClass);

    function WaitBootCompleteCommand() {
      return WaitBootCompleteCommand.__super__.constructor.apply(this, arguments);
    }

    return WaitBootCompleteCommand;

  })(Command);

  module.exports = WaitBootCompleteCommand;

}).call(this);

//# sourceMappingURL=WaitBootCompleteCommand.js.map
